/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author Someone
 */
public class MDI extends javax.swing.JFrame {

    /**
     * Creates new form MDI
     */
    public MDI() {
        initComponents();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar = new javax.swing.JMenuBar();
        mFile = new javax.swing.JMenu();
        TunDinas = new javax.swing.JMenuItem();
        TunPersonel = new javax.swing.JMenuItem();
        PidanaUmum = new javax.swing.JMenuItem();
        PidanaMiliter = new javax.swing.JMenuItem();
        PerdataPersonel = new javax.swing.JMenuItem();
        Exit = new javax.swing.JMenuItem();
        mReport = new javax.swing.JMenu();
        TUNDINAS = new javax.swing.JMenu();
        PerTriwulan = new javax.swing.JMenuItem();
        PerTanggal = new javax.swing.JMenuItem();
        PerKasus = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mFile.setText("File");

        TunDinas.setText("Perkara TUN Dinas");
        mFile.add(TunDinas);

        TunPersonel.setText("Perkara TUN Personel");
        mFile.add(TunPersonel);

        PidanaUmum.setText("Perkara Pidana Umum");
        mFile.add(PidanaUmum);

        PidanaMiliter.setText("Perkara Pidana Militer");
        mFile.add(PidanaMiliter);

        PerdataPersonel.setText("Perkara Perdata Personel");
        mFile.add(PerdataPersonel);

        Exit.setText("Exit");
        mFile.add(Exit);

        jMenuBar.add(mFile);

        mReport.setText("Report");

        TUNDINAS.setText("TUNDINAS");

        PerTriwulan.setText("Per Triwulan");
        TUNDINAS.add(PerTriwulan);

        PerTanggal.setText("Per Tanggal");
        TUNDINAS.add(PerTanggal);

        PerKasus.setText("Per Kasus");
        TUNDINAS.add(PerKasus);

        mReport.add(TUNDINAS);

        jMenuBar.add(mReport);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 417, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Exit;
    private javax.swing.JMenuItem PerKasus;
    private javax.swing.JMenuItem PerTanggal;
    private javax.swing.JMenuItem PerTriwulan;
    private javax.swing.JMenuItem PerdataPersonel;
    private javax.swing.JMenuItem PidanaMiliter;
    private javax.swing.JMenuItem PidanaUmum;
    private javax.swing.JMenu TUNDINAS;
    private javax.swing.JMenuItem TunDinas;
    private javax.swing.JMenuItem TunPersonel;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenu mFile;
    private javax.swing.JMenu mReport;
    // End of variables declaration//GEN-END:variables
}
