/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.ControlGenerateReport;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.text.DateFormat;
import java.text.SimpleDateFormat;

/**
 *
 * @author Someone
 */
public class ReportTunDinasTriwulan extends javax.swing.JFrame {

    /**
     * Creates new form ReportTunDinasTriwulan
     */
    public ReportTunDinasTriwulan() {
        initComponents();
        this.setVisible(true);
        this.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        setResizable(false);
        DateFormat dateFormat = new SimpleDateFormat("yyyy");
        String utilDate = dateFormat.format(new java.util.Date());
        txTahun.setValue(Integer.valueOf(utilDate));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tri1 = new javax.swing.JButton();
        tri2 = new javax.swing.JButton();
        tri3 = new javax.swing.JButton();
        tri4 = new javax.swing.JButton();
        txTahun = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Laporan");

        tri1.setText("Triwulan 1");
        tri1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tri1ActionPerformed(evt);
            }
        });

        tri2.setText("Triwulan 2");
        tri2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tri2ActionPerformed(evt);
            }
        });

        tri3.setText("Triwulan 3");
        tri3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tri3ActionPerformed(evt);
            }
        });

        tri4.setText("Triwulan 4");
        tri4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tri4ActionPerformed(evt);
            }
        });

        jLabel2.setText("tahun");

        jButton1.setText("Keluar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txTahun))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1)
                        .addComponent(tri1)
                        .addComponent(tri2)
                        .addComponent(tri3)
                        .addComponent(tri4)))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txTahun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tri1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tri2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tri3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tri4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tri1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tri1ActionPerformed
        // TODO add your handling code here:
        control.getDataTriwulan("I", String.valueOf((int)txTahun.getValue()));
        control.generateNow();
        this.setVisible(false);
    }//GEN-LAST:event_tri1ActionPerformed

    private void tri2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tri2ActionPerformed
        // TODO add your handling code here:
        control.getDataTriwulan("II", String.valueOf((int)txTahun.getValue()));
        control.generateNow();
        this.setVisible(false);
    }//GEN-LAST:event_tri2ActionPerformed

    private void tri3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tri3ActionPerformed
        // TODO add your handling code here:
        control.getDataTriwulan("III", String.valueOf((int)txTahun.getValue()));
        control.generateNow();
        this.setVisible(false);
    }//GEN-LAST:event_tri3ActionPerformed

    private void tri4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tri4ActionPerformed
        // TODO add your handling code here:
        control.getDataTriwulan("IV", String.valueOf((int)txTahun.getValue()));
        control.generateNow();
        this.setVisible(false);
    }//GEN-LAST:event_tri4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton tri1;
    private javax.swing.JButton tri2;
    private javax.swing.JButton tri3;
    private javax.swing.JButton tri4;
    private javax.swing.JSpinner txTahun;
    // End of variables declaration//GEN-END:variables
    
    private ControlGenerateReport control = new ControlGenerateReport();;
}

